# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PHYS 709, Fall 2024
tagline: Advanced Mechanics I
description: >-
  PHYS 709 "Advanced Mechanics I" at the University of Mississippi, Fall 2024.
  Instructor: Dr. Gavin S. Davies.
author: Gavin S. Davies
baseurl: '/PHYS709-Fall2024' # the subpath of your site, e.g. /blog
url: 'https://olemiss-physics.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE","README.md"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.9.0
color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  PHYS709 on GitHub:
    - 'https://github.com/olemiss-physics/PHYS709-Fall2024'
footer_content: "&copy; 2024 Gavin S. Davies. Released under the <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA</a> license."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

nav_external_links:
  - title: 'PHYS709 on GitHub'
    url: https://github.com/olemiss-physics/PHYS709-Fall2024
    hide_icon: false
    opens_in_new_tab: true
  - title: 'Slack'
    url: https://umphysics.slack.com/archives/C07JEJZ8LTD
    hide_icon: false
    opens_in_new_tab: true
  - title: 'GitHub repository'
    url: https://github.com/olemiss-physics/
    hide_icon: false
    opens_in_new_tab: true
  - title: 'Zoom'
    url: #
    hide_icon: false
    opens_in_new_tab: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

callouts:
  highlight:
    title: Highlight
    color: dracula-purple
  note:
    title: Note
    color: dracula-cyan
  note-optional:
    title: Optional
    color: dracula-yellow
  warning: 
    title: Warning
    color: dracula-orange
  danger:
    title: Danger
    color: dracula-red

enable_copy_code_button: true

